/* AUTO-GENERATED by scripts/generate_meter_pack.py — do not edit. */
#include "balansun_meter_registry.h"
#include "balansun_meter_driver_iface.h"
#include "balansun_meter_sources_enable.h"

#if BALANSUN_ENABLE_SOURCE_JSY_MK194
#include "../metering/jsy_mk194t_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_JSY_MK333
#include "../metering/jsy_mk333_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_ANALOG
#include "../metering/uxi_probe_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_LINKY
#include "../metering/linky_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_ENPHASE
#include "../metering/enphase_envoy_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_SHELLY_EM
#include "../metering/shelly_em_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_SHELLY_PRO
#include "../metering/shelly_pro_em_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_SMARTG
#include "../metering/smart_gateway_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_HOMEW
#include "../metering/homewizard_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_PMqtt
#include "../metering/pmqtt_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_VictronGx
#include "../metering/victron_gx_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_EXT
#include "../metering/external_peer_meter.h"
#endif
#if BALANSUN_ENABLE_SOURCE_NOTDEF
#include "../metering/bench_sim_meter.h"
#endif

IMeterDriver *const kMeterInstances[] = {
#if BALANSUN_ENABLE_SOURCE_JSY_MK194
  balansun_meter_instance_jsy_mk194(),
#endif
#if BALANSUN_ENABLE_SOURCE_JSY_MK333
  balansun_meter_instance_jsy_mk333(),
#endif
#if BALANSUN_ENABLE_SOURCE_ANALOG
  balansun_meter_instance_analog(),
#endif
#if BALANSUN_ENABLE_SOURCE_LINKY
  balansun_meter_instance_linky(),
#endif
#if BALANSUN_ENABLE_SOURCE_ENPHASE
  balansun_meter_instance_enphase(),
#endif
#if BALANSUN_ENABLE_SOURCE_SHELLY_EM
  balansun_meter_instance_shelly_em(),
#endif
#if BALANSUN_ENABLE_SOURCE_SHELLY_PRO
  balansun_meter_instance_shelly_pro(),
#endif
#if BALANSUN_ENABLE_SOURCE_SMARTG
  balansun_meter_instance_smartg(),
#endif
#if BALANSUN_ENABLE_SOURCE_HOMEW
  balansun_meter_instance_homew(),
#endif
#if BALANSUN_ENABLE_SOURCE_PMqtt
  balansun_meter_instance_pmqtt(),
#endif
#if BALANSUN_ENABLE_SOURCE_VictronGx
  balansun_meter_instance_victron_gx(),
#endif
#if BALANSUN_ENABLE_SOURCE_EXT
  balansun_meter_instance_balansun_peer(),
#endif
#if BALANSUN_ENABLE_SOURCE_NOTDEF
  balansun_meter_instance_notdef(),
#endif
};

size_t balansun_meter_instance_count() {
  return sizeof(kMeterInstances) / sizeof(kMeterInstances[0]);
}

IMeterDriver *balansun_meter_instance_at(size_t i) {
  if (i >= balansun_meter_instance_count()) return nullptr;
  return kMeterInstances[i];
}

IMeterDriver *balansun_meter_driver_for_id(SourceId id) {
  for (size_t i = 0; i < balansun_meter_instance_count(); ++i) {
    IMeterDriver *d = kMeterInstances[i];
    if (d && d->id() == id) return d;
  }
  return nullptr;
}

