#pragma once

/*
 * balansun_product_profile.h — Compile-time product role + meter pack (PlatformIO -D).
 * Meter selection: BALANSUN_METER_PACK in balansun_meter_pack.h (default = all meters).
 * Capabilities: BALANSUN_ROLE (triac, regulation, inject).
 */

#include "balansun_meter_pack.h"

#define BALANSUN_ROLE_FULL_ROUTER 1
#define BALANSUN_ROLE_METER_ROUTER 2
#define BALANSUN_ROLE_METER_GATEWAY 3

#ifndef BALANSUN_ROLE
#if defined(METER_ONLY_BUILD)
#define BALANSUN_ROLE BALANSUN_ROLE_METER_GATEWAY
#else
#define BALANSUN_ROLE BALANSUN_ROLE_FULL_ROUTER
#endif
#endif

/* Legacy profile ids — derived from role for caps/tests; prefer BALANSUN_ROLE + BALANSUN_METER_PACK. */
#define BALANSUN_PRODUCT_FULL_ROUTER 1
#define BALANSUN_PRODUCT_JSY_MK194_ROUTER 2
#define BALANSUN_PRODUCT_JSY_MK194_METER 3
#define BALANSUN_PRODUCT_METER_ONLY 4

#ifndef BALANSUN_PRODUCT_PROFILE
#if BALANSUN_ROLE == BALANSUN_ROLE_METER_GATEWAY
#define BALANSUN_PRODUCT_PROFILE BALANSUN_PRODUCT_METER_ONLY
#elif BALANSUN_ROLE == BALANSUN_ROLE_METER_ROUTER && BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK194
#define BALANSUN_PRODUCT_PROFILE BALANSUN_PRODUCT_JSY_MK194_ROUTER
#elif BALANSUN_ROLE == BALANSUN_ROLE_METER_GATEWAY && BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK194
#define BALANSUN_PRODUCT_PROFILE BALANSUN_PRODUCT_JSY_MK194_METER
#else
#define BALANSUN_PRODUCT_PROFILE BALANSUN_PRODUCT_FULL_ROUTER
#endif
#endif

#define BALANSUN_BOARD_GENERIC 0
#define BALANSUN_BOARD_ESP32_32U 1
#define BALANSUN_BOARD_ESP32_S3 2

#ifndef BALANSUN_BOARD_PROFILE
#define BALANSUN_BOARD_PROFILE BALANSUN_BOARD_GENERIC
#endif
