/* AUTO-GENERATED by scripts/generate_meter_pack.py — do not edit. */
#include "balansun_meter_pack.h"
#include "balansun_product_profile.h"

const char *balansun_meter_pack_id_wire(void) {
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK194
  return "jsy_mk194";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK333
  return "jsy_mk333";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ANALOG
  return "analog";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_LINKY
  return "linky";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ENPHASE
  return "enphase";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_EM
  return "shelly_em";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_PRO
  return "shelly_pro";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SMARTG
  return "smartg";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_HOMEW
  return "homew";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_PMqtt
  return "pmqtt";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_BALANSUN_PEER
  return "balansun_peer";
#endif
  return "full";
}

const char *balansun_meter_pack_default_wire(void) {
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK194
  return "JsyMk194";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK333
  return "JsyMk333";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ANALOG
  return "Analog";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_LINKY
  return "Linky";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ENPHASE
  return "Enphase";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_EM
  return "ShellyEm";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_PRO
  return "ShellyPro";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SMARTG
  return "SmartG";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_HOMEW
  return "HomeW";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_PMqtt
  return "Pmqtt";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_BALANSUN_PEER
  return "BalansunPeer";
#endif
  return "JsyMk194";
}

int balansun_meter_pack_is_single(void) {
  return BALANSUN_METER_PACK != BALANSUN_METER_PACK_FULL;
}

const char *balansun_product_profile_wire_compile_time(void) {
#if BALANSUN_ROLE == BALANSUN_ROLE_FULL_ROUTER
  return "full_router";
#elif BALANSUN_ROLE == BALANSUN_ROLE_METER_ROUTER
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK194
  return "jsy_mk194_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK333
  return "jsy_mk333_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ANALOG
  return "analog_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_LINKY
  return "linky_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ENPHASE
  return "enphase_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_EM
  return "shelly_em_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_PRO
  return "shelly_pro_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SMARTG
  return "smartg_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_HOMEW
  return "homew_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_PMqtt
  return "pmqtt_router";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_BALANSUN_PEER
  return "balansun_peer_router";
#endif
  return "meter_router";
#elif BALANSUN_ROLE == BALANSUN_ROLE_METER_GATEWAY
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK194
  return "jsy_mk194_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_JSY_MK333
  return "jsy_mk333_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ANALOG
  return "analog_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_LINKY
  return "linky_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_ENPHASE
  return "enphase_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_EM
  return "shelly_em_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SHELLY_PRO
  return "shelly_pro_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_SMARTG
  return "smartg_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_HOMEW
  return "homew_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_PMqtt
  return "pmqtt_meter";
#endif
#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_BALANSUN_PEER
  return "balansun_peer_meter";
#endif
  return "meter_gateway";
#else
  return "full_router";
#endif
}

