// AUTO-GENERATED by scripts/generate_meter_pack.py — do not edit.

import type { MeterGpioGroup } from "./sourceRegistry";

export type MeterDriverBaseKind =
  | "lanHttpJson"
  | "lanHttpCustom"
  | "serial"
  | "adc"
  | "tls"
  | "mqtt"
  | "bench";

export type SourceWireId =
  "JsyMk194"
  | "JsyMk333"
  | "Analog"
  | "Linky"
  | "Enphase"
  | "ShellyEm"
  | "ShellyPro"
  | "SmartG"
  | "HomeW"
  | "Pmqtt"
  | "VictronGx"
  | "BalansunPeer";

export type ConfigField =
  | "calib_i"
  | "calib_u"
  | "enphase_password"
  | "enphase_serial"
  | "enphase_user"
  | "ext_peer_ip"
  | "ext_peer_path"
  | "ext_peer_port"
  | "ext_protocol"
  | "jsy_mk333_serial_baud"
  | "meter_channel"
  | "pmqtt_bindings"
  | "pmqtt_schema"
  | "pmqtt_topic"
  | "tempo_rte_enabled"
  | "victron_battery_device_id"
  | "victron_broker_ip"
  | "victron_grid_phases"
  | "victron_portal_id"
  | "victron_surplus_mode";

export interface MeterSourceDefinition {
  id: SourceWireId;
  baseKind: MeterDriverBaseKind;
  connectionKind: "http" | "https" | "serial" | "adc" | "mqtt" | "bench";
  pinoutAnchor: string;
  meterGpio?: MeterGpioGroup[];
  uartPresenceId?: string;
  fields: ConfigField[];
}

export const GENERATED_SOURCE_REGISTRY: MeterSourceDefinition[] = [
  {
    id: "JsyMk194",
    baseKind: "serial",
    connectionKind: "serial",
    pinoutAnchor: "source_jsy_mk194",
    meterGpio: ["uart"],
    uartPresenceId: "jsy_mk194",
    fields: [],
  },
  {
    id: "JsyMk333",
    baseKind: "serial",
    connectionKind: "serial",
    pinoutAnchor: "source_jsy_mk333",
    meterGpio: ["uart"],
    uartPresenceId: "jsy_mk194",
    fields: ["jsy_mk333_serial_baud"],
  },
  {
    id: "Analog",
    baseKind: "adc",
    connectionKind: "adc",
    pinoutAnchor: "source_analog",
    meterGpio: ["analog"],
    fields: ["calib_u", "calib_i"],
  },
  {
    id: "Linky",
    baseKind: "serial",
    connectionKind: "serial",
    pinoutAnchor: "source_linky",
    meterGpio: ["uart"],
    fields: ["tempo_rte_enabled"],
  },
  {
    id: "Enphase",
    baseKind: "tls",
    connectionKind: "https",
    pinoutAnchor: "source_enphase",
    fields: ["enphase_user", "enphase_password", "enphase_serial", "meter_channel"],
  },
  {
    id: "ShellyEm",
    baseKind: "lanHttpCustom",
    connectionKind: "http",
    pinoutAnchor: "source_shellyem",
    fields: ["ext_peer_ip"],
  },
  {
    id: "ShellyPro",
    baseKind: "lanHttpCustom",
    connectionKind: "http",
    pinoutAnchor: "17-sources-de-mesure--schémas-électrique-et-électronique",
    fields: ["ext_peer_ip", "meter_channel"],
  },
  {
    id: "SmartG",
    baseKind: "lanHttpJson",
    connectionKind: "http",
    pinoutAnchor: "source_smartg",
    fields: ["ext_peer_ip"],
  },
  {
    id: "HomeW",
    baseKind: "lanHttpJson",
    connectionKind: "http",
    pinoutAnchor: "17-sources-de-mesure--schémas-électrique-et-électronique",
    fields: ["ext_peer_ip"],
  },
  {
    id: "Pmqtt",
    baseKind: "mqtt",
    connectionKind: "mqtt",
    pinoutAnchor: "17-sources-de-mesure--schémas-électrique-et-électronique",
    fields: ["pmqtt_topic", "pmqtt_schema", "pmqtt_bindings"],
  },
  {
    id: "VictronGx",
    baseKind: "mqtt",
    connectionKind: "mqtt",
    pinoutAnchor: "17-sources-de-mesure--schémas-électrique-et-électronique",
    fields: ["victron_broker_ip", "victron_portal_id", "victron_battery_device_id", "victron_surplus_mode", "victron_grid_phases"],
  },
  {
    id: "BalansunPeer",
    baseKind: "lanHttpCustom",
    connectionKind: "http",
    pinoutAnchor: "source_ext",
    fields: ["ext_peer_ip", "ext_peer_port", "ext_peer_path", "ext_protocol"],
  },
];
