// AUTO-GENERATED by scripts/generate_meter_pack.py — do not edit.

export interface TemperatureSensorDefinition {
  kind: "ds18b20";
  maxSlots: number;
  gpioOptions: number[];
  pinoutAnchor: string;
}

export const TEMPERATURE_SENSOR_REGISTRY: TemperatureSensorDefinition[] = [
  {
    kind: "ds18b20",
    maxSlots: 2,
    gpioOptions: [13, 21, 27, 33],
    pinoutAnchor: "6-ds18b20-sensor-1-wire--onewire-library--optional",
  },
];
