#pragma once

#ifndef ACTION_NODE_PIN_FULL
#define ACTION_NODE_PIN_FULL 5
#endif
#ifndef ACTION_NODE_PIN_HALF_NEG
#define ACTION_NODE_PIN_HALF_NEG 4
#endif
#ifndef ACTION_NODE_PIN_HALF_POS
#define ACTION_NODE_PIN_HALF_POS 0
#endif
#ifndef ACTION_NODE_PIN_DS18
#define ACTION_NODE_PIN_DS18 2
#endif

#ifndef BALANSUN_PILOT_WIRE_WIRING
#define BALANSUN_PILOT_WIRE_WIRING R2_FULL_3RELAY
#endif

#define R2_FULL_3RELAY 1
#define R2_FULL_2RELAY 2
