#!/usr/bin/env python3
"""Generate meter-pack headers and PlatformIO env fragment from meter_pack_manifest.json."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "firmware" / "metering" / "meter_pack_manifest.json"
OUT_PACK_H = ROOT / "firmware" / "core" / "balansun_meter_pack.h"
OUT_ENABLE_H = ROOT / "firmware" / "core" / "balansun_meter_pack_enable.generated.h"
OUT_PIO = ROOT / "platformio" / "meter_packs.ini"
OUT_MATRIX = ROOT / "firmware" / "test" / "golden" / "meter_pack_matrix.json"
OUT_INSTANCES_CPP = ROOT / "firmware" / "core" / "balansun_meter_instances.generated.cpp"
OUT_WIRE_INC = ROOT / "firmware" / "core" / "balansun_meter_wire_rows.generated.inc"
OUT_CAP_INC = ROOT / "firmware" / "core" / "balansun_config_cap_meter_rules.generated.inc"
OUT_WEB_REGISTRY = ROOT / "web" / "src" / "routes" / "settings" / "sourceRegistry.generated.ts"

WIRE_TO_SOURCE_ID = {
    "JsyMk194": "JsyMk194",
    "JsyMk333": "JsyMk333",
    "Analog": "Analog",
    "Linky": "Linky",
    "Enphase": "Enphase",
    "ShellyEm": "ShellyEm",
    "ShellyPro": "ShellyPro",
    "SmartG": "SmartG",
    "HomeW": "HomeW",
    "Pmqtt": "Pmqtt",
    "VictronGx": "VictronGx",
    "NotDef": "NotDef",
    "BalansunPeer": "BalansunPeer",
}

BASE_KIND_MAP = {
    "LanHttpJsonMeter": "lanHttpJson",
    "LanHttpCustomMeter": "lanHttpCustom",
    "SerialMeterDriver": "serial",
    "AdcMeterDriver": "adc",
    "TlsHttpMeter": "tls",
    "EventDrivenMeter": "mqtt",
    "MeterDriverBase": "bench",
}

TS_BANNER = "// AUTO-GENERATED by scripts/generate_meter_pack.py — do not edit.\n"

GENERATED_BANNER = "/* AUTO-GENERATED by scripts/generate_meter_pack.py — do not edit. */"


def load_manifest() -> dict:
    with MANIFEST.open(encoding="utf-8") as f:
        return json.load(f)


def all_enable_macros(manifest: dict) -> list[str]:
    macros = [manifest["notdef"]["enable_macro"]]
    for p in manifest["packs"]:
        macros.append(p["enable_macro"])
    return macros


def render_pack_h(manifest: dict) -> str:
    packs = manifest["packs"]
    lines = [
        GENERATED_BANNER,
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
        "/* Meter pack ids — default BALANSUN_METER_PACK_FULL compiles all meters. */",
        "#define BALANSUN_METER_PACK_FULL 0",
    ]
    for i, p in enumerate(packs, start=1):
        lines.append(f"#define {p['pack_macro']} {i}")
    factory_cases = []
    for i, p in enumerate(packs):
        macro = p["pack_macro"]
        wire = p["wire"]
        branch = "#if" if i == 0 else "#elif"
        factory_cases.append(f"{branch} BALANSUN_METER_PACK == {macro}")
        factory_cases.append(f'#define BALANSUN_METER_PACK_FACTORY_SOURCE_WIRE "{wire}"')
    factory_cases.append("#else")
    factory_cases.append('#define BALANSUN_METER_PACK_FACTORY_SOURCE_WIRE "JsyMk194"')
    factory_cases.append("#endif")

    lines += [
        "",
        "#ifndef BALANSUN_METER_PACK",
        "#define BALANSUN_METER_PACK BALANSUN_METER_PACK_FULL",
        "#endif",
        "",
        "#ifndef BALANSUN_METER_PACK_FACTORY_SOURCE_WIRE",
        *factory_cases,
        "#endif",
        "",
        "#ifdef __cplusplus",
        "extern \"C\" {",
        "#endif",
        "",
        "const char *balansun_meter_pack_id_wire(void);",
        "const char *balansun_meter_pack_default_wire(void);",
        "int balansun_meter_pack_is_single(void);",
        "const char *balansun_product_profile_wire_compile_time(void);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_pack_cpp(manifest: dict) -> str:
    packs = manifest["packs"]
    cases_id = []
    cases_wire = []
    cases_profile_router = []
    cases_profile_meter = []
    for p in packs:
        macro = p["pack_macro"]
        pid = p["id"]
        cases_id.append(f"#if BALANSUN_METER_PACK == {macro}")
        cases_id.append(f'  return "{pid}";')
        cases_id.append("#endif")
        cases_wire.append(f"#if BALANSUN_METER_PACK == {macro}")
        cases_wire.append(f'  return "{p["wire"]}";')
        cases_wire.append("#endif")
        cases_profile_router.append(f"#if BALANSUN_METER_PACK == {macro}")
        cases_profile_router.append(f'  return "{pid}_router";')
        cases_profile_router.append("#endif")
        cases_profile_meter.append(f"#if BALANSUN_METER_PACK == {macro}")
        cases_profile_meter.append(f'  return "{pid}_meter";')
        cases_profile_meter.append("#endif")

    body = [
        GENERATED_BANNER,
        '#include "balansun_meter_pack.h"',
        '#include "balansun_product_profile.h"',
        "",
        "const char *balansun_meter_pack_id_wire(void) {",
        *cases_id,
        '  return "full";',
        "}",
        "",
        "const char *balansun_meter_pack_default_wire(void) {",
        *cases_wire,
        '  return "JsyMk194";',
        "}",
        "",
        "int balansun_meter_pack_is_single(void) {",
        "  return BALANSUN_METER_PACK != BALANSUN_METER_PACK_FULL;",
        "}",
        "",
        "const char *balansun_product_profile_wire_compile_time(void) {",
        "#if BALANSUN_ROLE == BALANSUN_ROLE_FULL_ROUTER",
        '  return "full_router";',
        "#elif BALANSUN_ROLE == BALANSUN_ROLE_METER_ROUTER",
        *cases_profile_router,
        '  return "meter_router";',
        "#elif BALANSUN_ROLE == BALANSUN_ROLE_METER_GATEWAY",
        *cases_profile_meter,
        '  return "meter_gateway";',
        "#else",
        '  return "full_router";',
        "#endif",
        "}",
        "",
    ]
    return "\n".join(body) + "\n"


def render_enable_h(manifest: dict) -> str:
    macros = all_enable_macros(manifest)
    packs = manifest["packs"]
    notdef = manifest["notdef"]["enable_macro"]

    def define_block(values: dict[str, int]) -> list[str]:
        out = []
        for m in macros:
            v = values.get(m, 0)
            out.append(f"#ifndef {m}")
            out.append(f"#define {m} {v}")
            out.append(f"#endif")
        return out

    lines = [
        GENERATED_BANNER,
        "#pragma once",
        "",
        '#include "balansun_meter_pack.h"',
        "",
        "/* Core rule: PACK_FULL → all sources; single pack → exactly one source (+ optional NotDef override). */",
        "",
        "#if BALANSUN_METER_PACK == BALANSUN_METER_PACK_FULL",
    ]
    lines += define_block({m: 1 for m in macros})
    lines.append("#else")
    full_off = {m: 0 for m in macros}
    for p in packs:
        macro = p["pack_macro"]
        vals = dict(full_off)
        vals[p["enable_macro"]] = 1
        lines.append(f"#if BALANSUN_METER_PACK == {macro}")
        lines += define_block(vals)
        lines.append("#endif")
    lines += [
        "#endif",
        "",
        "/* NotDef: off for single-meter production packs unless build_flags override. */",
        "#if BALANSUN_METER_PACK != BALANSUN_METER_PACK_FULL",
        f"#ifndef {notdef}",
        f"#undef {notdef}",
        f"#define {notdef} 0",
        "#endif",
        "#endif",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_pio_ini(manifest: dict) -> str:
    lines = [
        "; AUTO-GENERATED by scripts/generate_meter_pack.py — do not edit.",
        "; Included from platformio.ini",
        "",
    ]
    for p in manifest["packs"]:
        pid = p["id"]
        pack_macro = p["pack_macro"]
        for role_suffix, role_flag, meter_only in (
            ("router", "BALANSUN_ROLE_METER_ROUTER", False),
            ("full_router", "BALANSUN_ROLE_FULL_ROUTER", False),
            ("meter", "BALANSUN_ROLE_METER_GATEWAY", True),
        ):
            env_name = f"{pid}_{role_suffix}"
            lines.append(f"[env:{env_name}]")
            lines.append("extends = env:wroom32")
            lines.append("build_flags =")
            lines.append("\t${env:wroom32.build_flags}")
            lines.append(f"\t-DBALANSUN_METER_PACK={pack_macro}")
            lines.append(f"\t-DBALANSUN_ROLE={role_flag}")
            if meter_only:
                lines.append("\t-DMETER_ONLY_BUILD=1")
            lines.append("")
    # Backward-compatible aliases
    lines += [
        "[env:esp32_32u_jsy_router]",
        "extends = env:jsy_mk194_router",
        "build_flags =",
        "\t${env:jsy_mk194_router.build_flags}",
        "\t-DBALANSUN_BOARD_PROFILE=BALANSUN_BOARD_ESP32_32U",
        "",
        "[env:esp32_32u_jsy_full_router]",
        "extends = env:jsy_mk194_full_router",
        "build_flags =",
        "\t${env:jsy_mk194_full_router.build_flags}",
        "\t-DBALANSUN_BOARD_PROFILE=BALANSUN_BOARD_ESP32_32U",
        "",
        "[env:esp32_32u_jsy_meter]",
        "extends = env:jsy_mk194_meter",
        "build_flags =",
        "\t${env:jsy_mk194_meter.build_flags}",
        "\t-DBALANSUN_BOARD_PROFILE=BALANSUN_BOARD_ESP32_32U",
        "",
    ]
    return "\n".join(lines) + "\n"


def all_meter_entries(manifest: dict) -> list[dict]:
    entries = []
    for p in manifest["packs"]:
        entries.append(p)
    nd = dict(manifest["notdef"])
    entries.append(nd)
    return entries


def flags_to_cpp(flags: list[str]) -> str:
    if not flags:
        return "BALANSUN_METER_RSF_NONE"
    parts = []
    if "poll_backoff" in flags:
        parts.append("BALANSUN_METER_RSF_POLL_BACKOFF")
    if "touch_last_ms" in flags:
        parts.append("BALANSUN_METER_RSF_TOUCH_LAST_MS")
    return " | ".join(parts) if parts else "BALANSUN_METER_RSF_NONE"


def render_instances_cpp(manifest: dict) -> str:
    lines = [
        GENERATED_BANNER,
        '#include "balansun_meter_registry.h"',
        '#include "balansun_meter_driver_iface.h"',
        '#include "balansun_meter_sources_enable.h"',
        "",
    ]
    for entry in all_meter_entries(manifest):
        lines.append(f"#if {entry['enable_macro']}")
        lines.append(f'#include "../metering/{entry["driver_header"]}"')
        lines.append("#endif")
    lines.append("")
    lines.append("IMeterDriver *const kMeterInstances[] = {")
    for entry in all_meter_entries(manifest):
        lines.append(f"#if {entry['enable_macro']}")
        lines.append(f"  {entry['instance_fn']}(),")
        lines.append("#endif")
    lines.append("};")
    lines.append("")
    lines.append("size_t balansun_meter_instance_count() {")
    lines.append("  return sizeof(kMeterInstances) / sizeof(kMeterInstances[0]);")
    lines.append("}")
    lines.append("")
    lines.append("IMeterDriver *balansun_meter_instance_at(size_t i) {")
    lines.append("  if (i >= balansun_meter_instance_count()) return nullptr;")
    lines.append("  return kMeterInstances[i];")
    lines.append("}")
    lines.append("")
    lines.append("IMeterDriver *balansun_meter_driver_for_id(SourceId id) {")
    lines.append("  for (size_t i = 0; i < balansun_meter_instance_count(); ++i) {")
    lines.append("    IMeterDriver *d = kMeterInstances[i];")
    lines.append("    if (d && d->id() == id) return d;")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_wire_inc(manifest: dict) -> str:
    lines = [GENERATED_BANNER]
    for entry in all_meter_entries(manifest):
        sid = WIRE_TO_SOURCE_ID[entry["wire"]]
        lines.append(f"#if {entry['enable_macro']}")
        lines.append(f"    {{SourceId::{sid}, \"{entry['wire']}\"}},")
        lines.append("#endif")
    return "\n".join(lines) + "\n"


def render_cap_inc(manifest: dict) -> str:
    lines = [GENERATED_BANNER]
    field_wire: dict[str, str] = {}
    priority = [
        "balansun_peer",
        "enphase",
        "shelly_pro",
        "shelly_em",
        "smartg",
        "homew",
        "pmqtt",
        "jsy_mk333",
        "analog",
        "linky",
    ]
    packs_by_id = {p["id"]: p for p in manifest["packs"]}
    for pid in priority:
        pack = packs_by_id.get(pid)
        if not pack:
            continue
        for field in pack.get("config_fields", []):
            field_wire[field] = pack["wire"]
    for field in sorted(field_wire.keys()):
        wire = field_wire[field]
        lines.append(
            f'    {{"{field}", BalansunConfigCapRuleKind::MeterWire, {{.meter_wire = "{wire}"}}}},'
        )
    return "\n".join(lines) + "\n"


def render_web_registry(manifest: dict) -> str:
    spa_packs = [p for p in manifest["packs"] if p.get("spa_visible", True)]
    wire_ids = [f'"{p["wire"]}"' for p in spa_packs]
    config_fields: set[str] = set()
    for p in manifest["packs"]:
        config_fields.update(p.get("config_fields", []))
    config_field_lines = [f'  | "{f}"' for f in sorted(config_fields)]
    if config_field_lines:
        config_field_lines[-1] = config_field_lines[-1] + ";"
    lines = [
        TS_BANNER,
        'import type { MeterGpioGroup } from "./sourceRegistry";',
        "",
        "export type MeterDriverBaseKind =",
        '  | "lanHttpJson"',
        '  | "lanHttpCustom"',
        '  | "serial"',
        '  | "adc"',
        '  | "tls"',
        '  | "mqtt"',
        '  | "bench";',
        "",
        "export type SourceWireId =",
    ]
    for i, w in enumerate(wire_ids):
        suffix = ";" if i == len(wire_ids) - 1 else ""
        sep = "  | " if i > 0 else "  "
        lines.append(f'{sep}{w}{suffix}')
    lines += ["", "export type ConfigField =", *config_field_lines, ""]
    lines += [
        "export interface MeterSourceDefinition {",
        "  id: SourceWireId;",
        "  baseKind: MeterDriverBaseKind;",
        '  connectionKind: "http" | "https" | "serial" | "adc" | "mqtt" | "bench";',
        "  pinoutAnchor: string;",
        "  meterGpio?: MeterGpioGroup[];",
        "  uartPresenceId?: string;",
        "  fields: ConfigField[];",
        "}",
        "",
        "export const GENERATED_SOURCE_REGISTRY: MeterSourceDefinition[] = [",
    ]
    for p in spa_packs:
        gpio = p.get("meter_gpio", [])
        gpio_ts = ", ".join(f'"{g}"' for g in gpio)
        meter_gpio = f'["{gpio[0]}"]' if len(gpio) == 1 else (f"[{gpio_ts}]" if gpio else "undefined")
        uart_id = p.get("uart_presence_id")
        uart_line = f'uartPresenceId: "{uart_id}",' if uart_id else ""
        fields = ", ".join(f'"{f}"' for f in p.get("config_fields", []))
        base_kind = BASE_KIND_MAP.get(p.get("driver_base", "MeterDriverBase"), "bench")
        conn = p.get("connection_kind", p.get("transport", "http"))
        lines.append("  {")
        lines.append(f'    id: "{p["wire"]}",')
        lines.append(f'    baseKind: "{base_kind}",')
        lines.append(f'    connectionKind: "{conn}",')
        lines.append(f'    pinoutAnchor: "{p.get("pinout_anchor", "")}",')
        if gpio:
            lines.append(f"    meterGpio: {meter_gpio},")
        if uart_id:
            lines.append(f"    {uart_line}")
        lines.append(f"    fields: [{fields}],")
        lines.append("  },")
    lines += ["];", ""]
    return "\n".join(lines)


def render_matrix(manifest: dict) -> str:
    matrix = {
        "version": manifest["version"],
        "full_pack": "BALANSUN_METER_PACK_FULL",
        "packs": [
            {
                "id": p["id"],
                "pack_macro": p["pack_macro"],
                "wire": p["wire"],
                "enable_macro": p["enable_macro"],
                "env_router": f"{p['id']}_router",
                "env_full_router": f"{p['id']}_full_router",
                "env_meter": f"{p['id']}_meter",
            }
            for p in manifest["packs"]
        ],
    }
    return json.dumps(matrix, indent=2) + "\n"


def write_outputs(manifest: dict) -> None:
    OUT_PACK_H.write_text(render_pack_h(manifest), encoding="utf-8")
    pack_cpp = ROOT / "firmware" / "core" / "balansun_meter_pack.cpp"
    pack_cpp.write_text(render_pack_cpp(manifest), encoding="utf-8")
    OUT_ENABLE_H.write_text(render_enable_h(manifest), encoding="utf-8")
    OUT_PIO.parent.mkdir(parents=True, exist_ok=True)
    OUT_PIO.write_text(render_pio_ini(manifest), encoding="utf-8")
    OUT_MATRIX.parent.mkdir(parents=True, exist_ok=True)
    OUT_MATRIX.write_text(render_matrix(manifest), encoding="utf-8")
    OUT_INSTANCES_CPP.write_text(render_instances_cpp(manifest), encoding="utf-8")
    OUT_WIRE_INC.write_text(render_wire_inc(manifest), encoding="utf-8")
    OUT_CAP_INC.write_text(render_cap_inc(manifest), encoding="utf-8")
    OUT_WEB_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    OUT_WEB_REGISTRY.write_text(render_web_registry(manifest), encoding="utf-8")


def check_stale() -> int:
    manifest = load_manifest()
    expected = {
        OUT_PACK_H: render_pack_h(manifest),
        ROOT / "firmware" / "core" / "balansun_meter_pack.cpp": render_pack_cpp(manifest),
        OUT_ENABLE_H: render_enable_h(manifest),
        OUT_PIO: render_pio_ini(manifest),
        OUT_MATRIX: render_matrix(manifest),
        OUT_INSTANCES_CPP: render_instances_cpp(manifest),
        OUT_WIRE_INC: render_wire_inc(manifest),
        OUT_CAP_INC: render_cap_inc(manifest),
        OUT_WEB_REGISTRY: render_web_registry(manifest),
    }
    stale = []
    for path, content in expected.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(path.relative_to(ROOT))
    if stale:
        print("generate_meter_pack: stale outputs:", ", ".join(str(p) for p in stale), file=sys.stderr)
        print("Run: python3 scripts/generate_meter_pack.py", file=sys.stderr)
        return 1
    print("generate_meter_pack: OK")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Exit 1 if generated files are stale")
    args = parser.parse_args()
    if args.check:
        return check_stale()
    manifest = load_manifest()
    write_outputs(manifest)
    print(f"Wrote meter pack artifacts ({len(manifest['packs'])} packs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
