import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    env: {
      // Vitest exposes BASE on import.meta.env; ignore accidental shell BASE=http://device
      BASE: "/",
      VITE_DOCS_SITE_ORIGIN: "https://balansun.clouded.fr",
    },
    environment: "node",
    include: [
      "src/**/*.test.ts",
      "src/**/*.dom.test.ts",
      "test/**/*.test.ts",
      "test/**/*.dom.test.ts",
    ],
    environmentMatchGlobs: [["**/*.dom.test.ts", "happy-dom"]],
    setupFiles: ["./test/setup-dom.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      include: [
        "src/utils/**",
        "src/api/configPut.ts",
        "src/api/publicBootstrap.ts",
        "src/api/apiSession.ts",
        "src/api/requestScheduler.ts",
        "src/routes/actions/**",
        "src/routes/settings/**",
        "src/components/**",
        "src/firmware/**",
        "src/navigationGuard.ts",
        "src/data/install-countries.ts",
        "src/brand/brandAssets.ts",
        "src/paths.ts",
        "src/paths.ts",
        "src/data/install-countries.ts",
      ],
      exclude: [
        "**/*.{test,dom.test}.ts",
        "src/i18n/locales/**",
        "src/api/types.ts",
        "src/vite-env.d.ts",
        "src/main.ts",
        "src/router.ts",
        "src/components/InstallBanner.ts",
        "src/components/Chart.ts",
        "src/components/Shell.ts",
        "src/components/SourceSetupWizard.ts",
        "src/components/JsonPathPicker.ts",
        "src/components/PmqttSetupFlow.ts",
        "src/components/KpiCard.ts",
        "src/components/TariffBadge.ts",
        "src/components/CacsiRegulationBanner.ts",
        "src/components/LegionellaGatingBanner.ts",
        "src/components/MeasurementSourceSummary.ts",
        "src/components/NetworkStatusSummary.ts",
        "src/components/MainsFrequencyBanner.ts",
        "src/components/TempoRteStatus.ts",
        "src/utils/settingsSwitch.ts",
        "src/routes/Settings.ts",
        "src/routes/settings/settingsLayout.ts",
        "src/routes/settings/settingsChrome.ts",
        "src/routes/settings/statusLedSettings.ts",
        "src/routes/settings/settingsRouterBridge.ts",
        "src/routes/settings/productTypeSettings.ts",
        "src/routes/settings/cards/advancedCard.ts",
        "src/routes/settings/cards/measurementCard.ts",
        "src/utils/pmqttPreview.ts",
        "src/utils/deviceTier.ts",
        "src/utils/adaptBackupForTarget.ts",
        "src/utils/backupApply.ts",
        "src/utils/documentTitle.ts",
        "src/components/ui/sectionCard.ts",
        "src/components/ResetDialog.ts",
        "src/routes/settings/statusLedEsp32s3.ts",
        "src/firmware/firmwareDailyCheck.ts",
        "src/firmware/githubDailyCheck.ts",
        "src/components/Toast.ts",
        "src/components/Dialog.ts",
        "src/utils/copyToClipboard.ts",
        "src/utils/tabsKeyboard.ts",
        "src/utils/historyEnergy.ts",
        "src/utils/historyPower.ts",
        "src/utils/jsonPathIndex.ts",
        "src/utils/pmqttBindings.ts",
        "src/routes/settings/settingsPaths.ts",
        "src/components/SelfTestPanel.ts",
        "src/routes/Actions.ts",
        "src/routes/Home.ts",
        "src/routes/History.ts",
        "src/routes/Firmware.ts",
        "src/routes/Diag.ts",
        "src/routes/WifiRouter.ts",
        "src/routes/WifiApSetup.ts",
        "src/routes/WifiStation.ts",
        "src/wifi/wifiForm.ts",
        "src/wifi/wifiPaths.ts",
        "src/routes/Backup.ts",
        "src/routes/firmwareUi.ts",
        "src/api/client.ts",
      ],
      thresholds: {
        lines: 95,
        statements: 95,
        branches: 95,
        functions: 95,
      },
    },
  },
});
